### ISSUE TITLE
Just one chunk ?

### ISSUE THREAD

**Issue by rom1504** [voxel/voxel-example#9]
It seems the world is not only flat but it is also small and you fall at the borders ![borders](http://static.tvtropes.org/pmwiki/pub/images/asterix_flatworld_8198.png)

Is it what's supposed to happen ? How do I make it work with an infinite world ?

**Comment by deathcap** [comment]
Are you seeing this with the latest http://voxel.github.io/voxel-example/ (updated yesterday)? Recently changed to use this new example generator: https://github.com/voxel/voxel-flatland - it's supposed to generate solid chunks infinitely in each direction (X,Z and Y<=0)

**Comment by rom1504** [comment]
Yes, I tried today, I'm seeing this with the latest commits. (also seeing this in http://voxel.github.io/voxel-example/)
when I move toward the border I see the next chunk appear then disapear a few ms later.

(and I'm doing https://github.com/rom1504/voxel-prismarine-world based on this example, which works, but I have the same problem as in this issue)

Edit: could this be related to this computer not having a real GPU ? I'll try with an other computer

edit2: nope, seeing the same thing on another computer, with both chrome and firefox

**Comment by deathcap** [comment]
Alright I'm able to reproduce this issue. The engine is actually displaying multiple chunks (which are 32x32x32), but it fails to show new chunks for some reason. What's weird is the problem does not occur with http://voxelmetaverse.com/  (which uses voxel-land, but it still doesn't occur if I disable land and load voxel-flatland instead), but it does with voxel-example, both using voxel-flatland and voxel-land. Will have to isolate how and where this broke.

<img width="1157" alt="screen shot 2016-01-19 at 8 41 06 pm" src="https://cloud.githubusercontent.com/assets/5897956/12440103/fea84030-beec-11e5-8d97-648391d45c1b.png">

**Comment by deathcap** [comment]
Got to the bottom of this, it's a conflict between the two modes of the engine's chunk generation. voxel-flatland (and voxel-land) must have `generateChunks: false` set in the voxel-engine-stackgl options. This is documented in [voxel-land](https://github.com/voxel/voxel-land) but wasn't in voxel-flatland; fixed in https://github.com/voxel/voxel-flatland/commit/23f11984ceabd30a3f9b0e3aacf963d3c80a4743, and it was missing in voxel-example, fixed in https://github.com/voxel/voxel-example/commit/54132eccfd208e76ee4ee9cd58c30b4c91e1291d (also published updated http://voxel.github.io/voxel-example/).
